#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    /* Compare the number of keys in each layer to a sample online. Correct? */
    /* Safer place for reset key? */

    LAYOUT(
        KC_GRAVE, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_LBRACKET, KC_RBRACKET, KC_BSPACE, KC_BSPACE,
        KC_TAB, KC_QUOTE, KC_COMMA, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLASH, KC_EQUAL, KC_BSLASH,
        KC_ESC, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_MINUS, KC_ENTER, KC_ENTER,
        KC_LSHIFT, KC_LSHIFT, KC_SCOLON, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_RSHIFT, KC_UP, TT(1),
        KC_LCTRL, TT(1), KC_LALT, KC_SPACE, KC_SPACE, KC_SPACE, KC_LGUI, KC_APP, KC_LEFT, KC_DOWN, KC_RIGHT),

	LAYOUT(
		KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_DEL, KC_DEL,
		KC_TRNS, KC_TRNS, KC_TRNS, RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRACKET,  KC_RBRACKET, KC_TRNS, KC_LBRACKET,  KC_RBRACKET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRANS
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INSERT, KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, DF(0), DF(0), DF(0), KC_TRNS, KC_TRNS, KC_HOME, KC_PGDOWN, KC_END),
};
